#! /usr/bin/env python

import os

output_file = open("test_inc.h", "w")
output_file.write('''/**
 * This file is automatically generated by a script.
 * DON'T MANUALLY CHANGE IT!
 */

''')

for root, dirs, files in os.walk('tests'):
  for file in files:
    if file[-2:] == ".h":
      test_name = file[:-2]
      output_file.write("BEGIN_TEST(%s, \"%s\")\n" % (test_name, test_name))
      output_file.write("#include \"%s/%s\"\n" % (root, file))
      output_file.write("END_TEST(%s)\n" % (test_name))
      output_file.write("\n")
output_file.close()

