/**
 * This file is automatically generated by a script.
 * DON'T MANUALLY CHANGE IT!
 */

BEGIN_TEST(matrix_linear_solver, "matrix_linear_solver")
#include "tests/matrix_linear_solver.h"
END_TEST(matrix_linear_solver)

BEGIN_TEST(identity_matrix, "identity_matrix")
#include "tests/identity_matrix.h"
END_TEST(identity_matrix)

BEGIN_TEST(various_vector_products, "various_vector_products")
#include "tests/various_vector_products.h"
END_TEST(various_vector_products)

BEGIN_TEST(matrix_resize, "matrix_resize")
#include "tests/matrix_resize.h"
END_TEST(matrix_resize)

BEGIN_TEST(vector_basic, "vector_basic")
#include "tests/vector_basic.h"
END_TEST(vector_basic)

BEGIN_TEST(matrix_getter, "matrix_getter")
#include "tests/matrix_getter.h"
END_TEST(matrix_getter)

BEGIN_TEST(matrix_getrow_getcol, "matrix_getrow_getcol")
#include "tests/matrix_getrow_getcol.h"
END_TEST(matrix_getrow_getcol)

BEGIN_TEST(matrix_block_replace, "matrix_block_replace")
#include "tests/matrix_block_replace.h"
END_TEST(matrix_block_replace)

BEGIN_TEST(matrix_inverse, "matrix_inverse")
#include "tests/matrix_inverse.h"
END_TEST(matrix_inverse)

BEGIN_TEST(matrix_adjoint_transpose_conjugate, "matrix_adjoint_transpose_conjugate")
#include "tests/matrix_adjoint_transpose_conjugate.h"
END_TEST(matrix_adjoint_transpose_conjugate)

BEGIN_TEST(matrix_arithmetic_operations, "matrix_arithmetic_operations")
#include "tests/matrix_arithmetic_operations.h"
END_TEST(matrix_arithmetic_operations)

BEGIN_TEST(various_matrix_type, "various_matrix_type")
#include "tests/various_matrix_type.h"
END_TEST(various_matrix_type)

BEGIN_TEST(matrix_compare, "matrix_compare")
#include "tests/matrix_compare.h"
END_TEST(matrix_compare)

BEGIN_TEST(matrix_assignment, "matrix_assignment")
#include "tests/matrix_assignment.h"
END_TEST(matrix_assignment)

BEGIN_TEST(matrix_eigen_solver, "matrix_eigen_solver")
#include "tests/matrix_eigen_solver.h"
END_TEST(matrix_eigen_solver)

BEGIN_TEST(matrix_index, "matrix_index")
#include "tests/matrix_index.h"
END_TEST(matrix_index)

