/**
 * This file is automatically generated by a script.
 * DON'T MANUALLY CHANGE IT!
 */

BEGIN_TEST(matrix_linear_solver, "matrix_linear_solver")
#include "tests/matrix_linear_solver.h"
END_TEST(matrix_linear_solver)

BEGIN_TEST(matrix_basic, "matrix_basic")
#include "tests/matrix_basic.h"
END_TEST(matrix_basic)

BEGIN_TEST(identity_matrix, "identity_matrix")
#include "tests/identity_matrix.h"
END_TEST(identity_matrix)

BEGIN_TEST(matrix_resize, "matrix_resize")
#include "tests/matrix_resize.h"
END_TEST(matrix_resize)

BEGIN_TEST(vector_basic, "vector_basic")
#include "tests/vector_basic.h"
END_TEST(vector_basic)

BEGIN_TEST(vector_math, "vector_math")
#include "tests/vector_math.h"
END_TEST(vector_math)

BEGIN_TEST(vector_products, "vector_products")
#include "tests/vector_products.h"
END_TEST(vector_products)

BEGIN_TEST(matrix_statistics, "matrix_statistics")
#include "tests/matrix_statistics.h"
END_TEST(matrix_statistics)

BEGIN_TEST(matrix_getter, "matrix_getter")
#include "tests/matrix_getter.h"
END_TEST(matrix_getter)

BEGIN_TEST(matrix_getrow_getcol, "matrix_getrow_getcol")
#include "tests/matrix_getrow_getcol.h"
END_TEST(matrix_getrow_getcol)

BEGIN_TEST(vector_statistics, "vector_statistics")
#include "tests/vector_statistics.h"
END_TEST(vector_statistics)

BEGIN_TEST(matrix_block_replace, "matrix_block_replace")
#include "tests/matrix_block_replace.h"
END_TEST(matrix_block_replace)

BEGIN_TEST(random, "random")
#include "tests/random.h"
END_TEST(random)

BEGIN_TEST(vector_fitting, "vector_fitting")
#include "tests/vector_fitting.h"
END_TEST(vector_fitting)

BEGIN_TEST(matrix_types, "matrix_types")
#include "tests/matrix_types.h"
END_TEST(matrix_types)

BEGIN_TEST(matrix_products, "matrix_products")
#include "tests/matrix_products.h"
END_TEST(matrix_products)

BEGIN_TEST(matrix_inverse, "matrix_inverse")
#include "tests/matrix_inverse.h"
END_TEST(matrix_inverse)

BEGIN_TEST(matrix_adjoint_transpose_conjugate, "matrix_adjoint_transpose_conjugate")
#include "tests/matrix_adjoint_transpose_conjugate.h"
END_TEST(matrix_adjoint_transpose_conjugate)

BEGIN_TEST(matrix_map_math, "matrix_map_math")
#include "tests/matrix_map_math.h"
END_TEST(matrix_map_math)

BEGIN_TEST(matrix_arithmetic_operations, "matrix_arithmetic_operations")
#include "tests/matrix_arithmetic_operations.h"
END_TEST(matrix_arithmetic_operations)

BEGIN_TEST(matrix_compare, "matrix_compare")
#include "tests/matrix_compare.h"
END_TEST(matrix_compare)

BEGIN_TEST(matrix_assignment, "matrix_assignment")
#include "tests/matrix_assignment.h"
END_TEST(matrix_assignment)

BEGIN_TEST(comma_initializer, "comma_initializer")
#include "tests/comma_initializer.h"
END_TEST(comma_initializer)

BEGIN_TEST(vector_map_math, "vector_map_math")
#include "tests/vector_map_math.h"
END_TEST(vector_map_math)

BEGIN_TEST(matrix_eigen_solver, "matrix_eigen_solver")
#include "tests/matrix_eigen_solver.h"
END_TEST(matrix_eigen_solver)

BEGIN_TEST(matrix_index, "matrix_index")
#include "tests/matrix_index.h"
END_TEST(matrix_index)

