# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_juzhen', [dirname(__file__)])
        except ImportError:
            import _juzhen
            return _juzhen
        if fp is not None:
            try:
                _mod = imp.load_module('_juzhen', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _juzhen = swig_import_helper()
    del swig_import_helper
else:
    import _juzhen
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Complex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Complex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Complex, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _juzhen.new_Complex(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _juzhen.delete_Complex
    __del__ = lambda self : None;
    def __eq__(self, *args): return _juzhen.Complex___eq__(self, *args)
    def __ne__(self, *args): return _juzhen.Complex___ne__(self, *args)
    def __str__(self): return _juzhen.Complex___str__(self)
    def __add__(self, *args): return _juzhen.Complex___add__(self, *args)
    def __sub__(self, *args): return _juzhen.Complex___sub__(self, *args)
    def __mul__(self, *args): return _juzhen.Complex___mul__(self, *args)
    def __div__(self, *args): return _juzhen.Complex___div__(self, *args)
    def conj(self): return _juzhen.Complex_conj(self)
    def abs(self): return _juzhen.Complex_abs(self)
    __swig_setmethods__["real"] = _juzhen.Complex_real_set
    __swig_getmethods__["real"] = _juzhen.Complex_real_get
    if _newclass:real = _swig_property(_juzhen.Complex_real_get, _juzhen.Complex_real_set)
    __swig_setmethods__["imag"] = _juzhen.Complex_imag_set
    __swig_getmethods__["imag"] = _juzhen.Complex_imag_get
    if _newclass:imag = _swig_property(_juzhen.Complex_imag_get, _juzhen.Complex_imag_set)
Complex_swigregister = _juzhen.Complex_swigregister
Complex_swigregister(Complex)

class Matrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Matrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Matrix, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _juzhen.new_Matrix(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _juzhen.delete_Matrix
    __del__ = lambda self : None;
    def __eq__(self, *args): return _juzhen.Matrix___eq__(self, *args)
    def __ne__(self, *args): return _juzhen.Matrix___ne__(self, *args)
    def num_row(self): return _juzhen.Matrix_num_row(self)
    def num_col(self): return _juzhen.Matrix_num_col(self)
    def size(self): return _juzhen.Matrix_size(self)
    def resize(self, *args): return _juzhen.Matrix_resize(self, *args)
    def clear(self): return _juzhen.Matrix_clear(self)
    def conj(self): return _juzhen.Matrix_conj(self)
    def trans(self): return _juzhen.Matrix_trans(self)
    def adj(self): return _juzhen.Matrix_adj(self)
    def get_col(self, *args): return _juzhen.Matrix_get_col(self, *args)
    def get_row(self, *args): return _juzhen.Matrix_get_row(self, *args)
    def block(self, *args): return _juzhen.Matrix_block(self, *args)
    def replace(self, *args): return _juzhen.Matrix_replace(self, *args)
    def swap_col(self, *args): return _juzhen.Matrix_swap_col(self, *args)
    def swap_row(self, *args): return _juzhen.Matrix_swap_row(self, *args)
    def __str__(self): return _juzhen.Matrix___str__(self)
    def __getitem__(self, *args): return _juzhen.Matrix___getitem__(self, *args)
    def copy(self): return _juzhen.Matrix_copy(self)
    def set(self, *args): return _juzhen.Matrix_set(self, *args)
    def get(self, *args): return _juzhen.Matrix_get(self, *args)
    def __add__(self, *args): return _juzhen.Matrix___add__(self, *args)
    def __sub__(self, *args): return _juzhen.Matrix___sub__(self, *args)
    def __mul__(self, *args): return _juzhen.Matrix___mul__(self, *args)
    def __div__(self, *args): return _juzhen.Matrix___div__(self, *args)
    def real(self): return _juzhen.Matrix_real(self)
    def imag(self): return _juzhen.Matrix_imag(self)
    def abs(self): return _juzhen.Matrix_abs(self)
    def abs2(self): return _juzhen.Matrix_abs2(self)
    def inverse(self): return _juzhen.Matrix_inverse(self)
    def linear_solver(self, *args): return _juzhen.Matrix_linear_solver(self, *args)
    def eigen(self, *args): return _juzhen.Matrix_eigen(self, *args)
    def left_eigen(self, *args): return _juzhen.Matrix_left_eigen(self, *args)
    def right_eigen(self, *args): return _juzhen.Matrix_right_eigen(self, *args)
Matrix_swigregister = _juzhen.Matrix_swigregister
Matrix_swigregister(Matrix)

class CMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CMatrix, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _juzhen.new_CMatrix(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _juzhen.delete_CMatrix
    __del__ = lambda self : None;
    def __eq__(self, *args): return _juzhen.CMatrix___eq__(self, *args)
    def __ne__(self, *args): return _juzhen.CMatrix___ne__(self, *args)
    def num_row(self): return _juzhen.CMatrix_num_row(self)
    def num_col(self): return _juzhen.CMatrix_num_col(self)
    def size(self): return _juzhen.CMatrix_size(self)
    def resize(self, *args): return _juzhen.CMatrix_resize(self, *args)
    def clear(self): return _juzhen.CMatrix_clear(self)
    def conj(self): return _juzhen.CMatrix_conj(self)
    def trans(self): return _juzhen.CMatrix_trans(self)
    def adj(self): return _juzhen.CMatrix_adj(self)
    def get_col(self, *args): return _juzhen.CMatrix_get_col(self, *args)
    def get_row(self, *args): return _juzhen.CMatrix_get_row(self, *args)
    def block(self, *args): return _juzhen.CMatrix_block(self, *args)
    def replace(self, *args): return _juzhen.CMatrix_replace(self, *args)
    def swap_col(self, *args): return _juzhen.CMatrix_swap_col(self, *args)
    def swap_row(self, *args): return _juzhen.CMatrix_swap_row(self, *args)
    def __str__(self): return _juzhen.CMatrix___str__(self)
    def __getitem__(self, *args): return _juzhen.CMatrix___getitem__(self, *args)
    def copy(self): return _juzhen.CMatrix_copy(self)
    def set(self, *args): return _juzhen.CMatrix_set(self, *args)
    def get(self, *args): return _juzhen.CMatrix_get(self, *args)
    def __add__(self, *args): return _juzhen.CMatrix___add__(self, *args)
    def __sub__(self, *args): return _juzhen.CMatrix___sub__(self, *args)
    def __mul__(self, *args): return _juzhen.CMatrix___mul__(self, *args)
    def __div__(self, *args): return _juzhen.CMatrix___div__(self, *args)
    def real(self): return _juzhen.CMatrix_real(self)
    def imag(self): return _juzhen.CMatrix_imag(self)
    def abs(self): return _juzhen.CMatrix_abs(self)
    def abs2(self): return _juzhen.CMatrix_abs2(self)
    def inverse(self): return _juzhen.CMatrix_inverse(self)
    def linear_solver(self, *args): return _juzhen.CMatrix_linear_solver(self, *args)
    def eigen(self, *args): return _juzhen.CMatrix_eigen(self, *args)
    def left_eigen(self, *args): return _juzhen.CMatrix_left_eigen(self, *args)
    def right_eigen(self, *args): return _juzhen.CMatrix_right_eigen(self, *args)
CMatrix_swigregister = _juzhen.CMatrix_swigregister
CMatrix_swigregister(CMatrix)


def Identity(*args):
  return _juzhen.Identity(*args)
Identity = _juzhen.Identity

def CIdentity(*args):
  return _juzhen.CIdentity(*args)
CIdentity = _juzhen.CIdentity
class Vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _juzhen.new_Vector(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _juzhen.delete_Vector
    __del__ = lambda self : None;
    def __eq__(self, *args): return _juzhen.Vector___eq__(self, *args)
    def __ne__(self, *args): return _juzhen.Vector___ne__(self, *args)
    def size(self): return _juzhen.Vector_size(self)
    def resize(self, *args): return _juzhen.Vector_resize(self, *args)
    def clear(self): return _juzhen.Vector_clear(self)
    def conj(self): return _juzhen.Vector_conj(self)
    def trans(self): return _juzhen.Vector_trans(self)
    def adj(self): return _juzhen.Vector_adj(self)
    def Sort(self): return _juzhen.Vector_Sort(self)
    def block(self, *args): return _juzhen.Vector_block(self, *args)
    def replace(self, *args): return _juzhen.Vector_replace(self, *args)
    def swap(self, *args): return _juzhen.Vector_swap(self, *args)
    def __str__(self): return _juzhen.Vector___str__(self)
    def __getitem__(self, *args): return _juzhen.Vector___getitem__(self, *args)
    def copy(self): return _juzhen.Vector_copy(self)
    def set(self, *args): return _juzhen.Vector_set(self, *args)
    def get(self, *args): return _juzhen.Vector_get(self, *args)
    def __add__(self, *args): return _juzhen.Vector___add__(self, *args)
    def __sub__(self, *args): return _juzhen.Vector___sub__(self, *args)
    def __mul__(self, *args): return _juzhen.Vector___mul__(self, *args)
    def __div__(self, *args): return _juzhen.Vector___div__(self, *args)
    def real(self): return _juzhen.Vector_real(self)
    def imag(self): return _juzhen.Vector_imag(self)
    def abs(self): return _juzhen.Vector_abs(self)
    def abs2(self): return _juzhen.Vector_abs2(self)
Vector_swigregister = _juzhen.Vector_swigregister
Vector_swigregister(Vector)

class CVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CVector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _juzhen.new_CVector(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _juzhen.delete_CVector
    __del__ = lambda self : None;
    def __eq__(self, *args): return _juzhen.CVector___eq__(self, *args)
    def __ne__(self, *args): return _juzhen.CVector___ne__(self, *args)
    def size(self): return _juzhen.CVector_size(self)
    def resize(self, *args): return _juzhen.CVector_resize(self, *args)
    def clear(self): return _juzhen.CVector_clear(self)
    def conj(self): return _juzhen.CVector_conj(self)
    def trans(self): return _juzhen.CVector_trans(self)
    def adj(self): return _juzhen.CVector_adj(self)
    def block(self, *args): return _juzhen.CVector_block(self, *args)
    def replace(self, *args): return _juzhen.CVector_replace(self, *args)
    def swap(self, *args): return _juzhen.CVector_swap(self, *args)
    def __str__(self): return _juzhen.CVector___str__(self)
    def __getitem__(self, *args): return _juzhen.CVector___getitem__(self, *args)
    def copy(self): return _juzhen.CVector_copy(self)
    def set(self, *args): return _juzhen.CVector_set(self, *args)
    def get(self, *args): return _juzhen.CVector_get(self, *args)
    def __add__(self, *args): return _juzhen.CVector___add__(self, *args)
    def __sub__(self, *args): return _juzhen.CVector___sub__(self, *args)
    def __mul__(self, *args): return _juzhen.CVector___mul__(self, *args)
    def __div__(self, *args): return _juzhen.CVector___div__(self, *args)
    def real(self): return _juzhen.CVector_real(self)
    def imag(self): return _juzhen.CVector_imag(self)
    def abs(self): return _juzhen.CVector_abs(self)
    def abs2(self): return _juzhen.CVector_abs2(self)
CVector_swigregister = _juzhen.CVector_swigregister
CVector_swigregister(CVector)

def inverse(a):
    return a.inverse()

def linear_solver(a, b):
    return a.linear_solver(b)

def eigen(a):
    e = CMatrix()
    if type(a).__name__ == "Matrix":
      vl = Matrix()
      vr = Matrix()
    else:
      vl = CMatrix()
      vr = CMatrix()
    a.eigen(e, vl, vr)
    return (e, vl, vr)

def right_eigen(a):
    e = CMatrix()
    if type(a).__name__ == "Matrix":
      vr = Matrix()
    else:
      vr = CMatrix()
    a.right_eigen(e, vr)
    return (e, vr)

def left_eigen(a):
    e = CMatrix()
    if type(a).__name__ == "Matrix":
      vr = Matrix()
    else:
      vr = CMatrix()
    a.left_eigen(e, vr)
    return (e, vr)



def sort(*args):
  return _juzhen.sort(*args)
sort = _juzhen.sort

def cov(*args):
  return _juzhen.cov(*args)
cov = _juzhen.cov

def var(*args):
  return _juzhen.var(*args)
var = _juzhen.var

def std_dev(*args):
  return _juzhen.std_dev(*args)
std_dev = _juzhen.std_dev

def corr_coeff(*args):
  return _juzhen.corr_coeff(*args)
corr_coeff = _juzhen.corr_coeff


def det(*args):
  return _juzhen.det(*args)
det = _juzhen.det

def transpose(*args):
  return _juzhen.transpose(*args)
transpose = _juzhen.transpose

def adjoint(*args):
  return _juzhen.adjoint(*args)
adjoint = _juzhen.adjoint

def conjugate(*args):
  return _juzhen.conjugate(*args)
conjugate = _juzhen.conjugate

def join(*args):
  return _juzhen.join(*args)
join = _juzhen.join

def outer_product(*args):
  return _juzhen.outer_product(*args)
outer_product = _juzhen.outer_product

def cross_product(*args):
  return _juzhen.cross_product(*args)
cross_product = _juzhen.cross_product

def sum(*args):
  return _juzhen.sum(*args)
sum = _juzhen.sum

def prod(*args):
  return _juzhen.prod(*args)
prod = _juzhen.prod

def mean(*args):
  return _juzhen.mean(*args)
mean = _juzhen.mean

def norm_square(*args):
  return _juzhen.norm_square(*args)
norm_square = _juzhen.norm_square

def norm(*args):
  return _juzhen.norm(*args)
norm = _juzhen.norm

def norm_one(*args):
  return _juzhen.norm_one(*args)
norm_one = _juzhen.norm_one

def norm_infinity(*args):
  return _juzhen.norm_infinity(*args)
norm_infinity = _juzhen.norm_infinity

def max(*args):
  return _juzhen.max(*args)
max = _juzhen.max

def min(*args):
  return _juzhen.min(*args)
min = _juzhen.min

def randomize(*args):
  return _juzhen.randomize(*args)
randomize = _juzhen.randomize

def least_squares_method(*args):
  return _juzhen.least_squares_method(*args)
least_squares_method = _juzhen.least_squares_method

def trace(*args):
  return _juzhen.trace(*args)
trace = _juzhen.trace

def schur_product(*args):
  return _juzhen.schur_product(*args)
schur_product = _juzhen.schur_product

def kronecker_product(*args):
  return _juzhen.kronecker_product(*args)
kronecker_product = _juzhen.kronecker_product

def inner_product(*args):
  return _juzhen.inner_product(*args)
inner_product = _juzhen.inner_product

def cos(*args):
  return _juzhen.cos(*args)
cos = _juzhen.cos

def sin(*args):
  return _juzhen.sin(*args)
sin = _juzhen.sin

def tan(*args):
  return _juzhen.tan(*args)
tan = _juzhen.tan

def acos(*args):
  return _juzhen.acos(*args)
acos = _juzhen.acos

def asin(*args):
  return _juzhen.asin(*args)
asin = _juzhen.asin

def atan(*args):
  return _juzhen.atan(*args)
atan = _juzhen.atan

def cosh(*args):
  return _juzhen.cosh(*args)
cosh = _juzhen.cosh

def sinh(*args):
  return _juzhen.sinh(*args)
sinh = _juzhen.sinh

def tanh(*args):
  return _juzhen.tanh(*args)
tanh = _juzhen.tanh

def exp(*args):
  return _juzhen.exp(*args)
exp = _juzhen.exp

def log(*args):
  return _juzhen.log(*args)
log = _juzhen.log

def log10(*args):
  return _juzhen.log10(*args)
log10 = _juzhen.log10

def sqrt(*args):
  return _juzhen.sqrt(*args)
sqrt = _juzhen.sqrt

def ceil(*args):
  return _juzhen.ceil(*args)
ceil = _juzhen.ceil

def fabs(*args):
  return _juzhen.fabs(*args)
fabs = _juzhen.fabs

def floor(*args):
  return _juzhen.floor(*args)
floor = _juzhen.floor

